services:
  step-ca:
    image: smallstep/step-ca:latest
    container_name: step-ca
    environment:
      - STEP_CA_PASSWORD_FILE=/run/secrets/password
      - DOCKER_STEPCA_INIT_NAME=smallstep  # Use = instead of :
      - DOCKER_STEPCA_INIT_DNS_NAMES=localhost  # Use = instead of :
    secrets:
      - password
    volumes:
      - ./step/config:/home/step/.step
    ports:
      - "4433:4433"  # Port for ACME HTTP-01 challenge
    command: ["step-ca", "/home/step/.step/config/ca.json"]

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   depends_on:
  #     - step-ca
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./certs:/etc/nginx/certs
  #   ports:
  #     - "443:443"  # HTTPS port
  #   networks:
  #     - ca-network

secrets:
  password:
    file: ./step/secrets/password


