version: '3.8'

services:
  step-ca:
    image: smallstep/step-ca:latest
    container_name: step-ca
    environment:
      - STEP_CA_PASSWORD_FILE=/run/secrets/password
    secrets:
      - password
    volumes:
      - ./step/config:/home/step/.step
    ports:
      - "4433:4433"  # Port for ACME HTTP-01 challenge
    networks:
      - ca-network
    command: ["step-ca", "/home/step/.step/config/ca.json"]

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - step-ca
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    ports:
      - "443:443"  # HTTPS port
    networks:
      - ca-network

secrets:
  password:
    file: ./step/secrets/password

networks:
  ca-network:
    driver: bridge

